# Generated by Django 2.0.6 on 2018-07-11 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Nome do Evento')),
                ('description', models.TextField()),
                ('kind', models.IntegerField(choices=[(1, 'Pesquisa'), (2, 'Ensino'), (3, 'Extensão')], default=1)),
                ('local', models.CharField(max_length=45)),
                ('organization', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_date', models.DateField()),
                ('workload', models.TimeField(default=0)),
                ('banner', models.ImageField(help_text='Resolução recomendada: 1000x300 px', upload_to='events_banners')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Inscrit@'), (2, 'Presente'), (3, 'Ausente')], default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'user')},
        ),
    ]
