# Generated by Django 2.0.6 on 2018-07-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
